services:
  accounts:
    image: "bhanudasrane01/accounts:s4"
    ports:
      - "8080:8080"
    container_name: accounts-ms
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybanks
  loans:
    image: "bhanudasrane01/loans:s4"
    ports:
      - "8090:8090"
    container_name: loans-ms
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybanks

  cards:
    image: "bhanudasrane01/cards:s4"
    ports:
      - "9000:9000"
    container_name: cards-ms
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybanks
networks:
  eazybanks:
    driver: "bridge"

